#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
#
# Source0 file verified with key 0xE9CBDFC0ABC0A854 (scdbackup@gmx.net)
#
Name     : xorriso
Version  : 1.5.6
Release  : 27
URL      : https://mirrors.kernel.org/gnu/xorriso/xorriso-1.5.6.tar.gz
Source0  : https://mirrors.kernel.org/gnu/xorriso/xorriso-1.5.6.tar.gz
Source1  : https://mirrors.kernel.org/gnu/xorriso/xorriso-1.5.6.tar.gz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 GPL-3.0 LGPL-2.1
Requires: xorriso-bin = %{version}-%{release}
Requires: xorriso-info = %{version}-%{release}
Requires: xorriso-license = %{version}-%{release}
Requires: xorriso-man = %{version}-%{release}
BuildRequires : acl-dev
BuildRequires : buildreq-configure
BuildRequires : bzip2-dev
BuildRequires : pkgconfig(zlib)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
------------------------------------------------------------------------------
Contribution of libburnia-project.org to the GNU Operating System
------------------------------------------------------------------------------
GNU xorriso. By Thomas Schmitt <scdbackup@gmx.net>
Derived from and supported by libburnia-project.org, published via:
http://www.gnu.org/software/xorriso/xorriso_eng.html
http://www.gnu.org/software/xorriso/xorriso-1.5.6.tar.gz
Provided under GPL version 3 or later. No warranty.
------------------------------------------------------------------------------

%package bin
Summary: bin components for the xorriso package.
Group: Binaries
Requires: xorriso-license = %{version}-%{release}

%description bin
bin components for the xorriso package.


%package info
Summary: info components for the xorriso package.
Group: Default

%description info
info components for the xorriso package.


%package license
Summary: license components for the xorriso package.
Group: Default

%description license
license components for the xorriso package.


%package man
Summary: man components for the xorriso package.
Group: Default

%description man
man components for the xorriso package.


%prep
%setup -q -n xorriso-1.5.6
cd %{_builddir}/xorriso-1.5.6
pushd ..
cp -a xorriso-1.5.6 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1686179372
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
%configure --disable-static
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3"
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3"
%configure --disable-static
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../buildavx2;
make %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1686179372
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/xorriso
cp %{_builddir}/xorriso-%{version}/COPYING %{buildroot}/usr/share/package-licenses/xorriso/8624bcdae55baeef00cd11d5dfcfa60f68710a02 || :
cp %{_builddir}/xorriso-%{version}/COPYRIGHT %{buildroot}/usr/share/package-licenses/xorriso/431ac668b8e0901320f42864b3f9361854690ff2 || :
cp %{_builddir}/xorriso-%{version}/libburn/COPYRIGHT %{buildroot}/usr/share/package-licenses/xorriso/a640a4b001c62a6f231213c9e10d5b985b05288b || :
cp %{_builddir}/xorriso-%{version}/libisoburn/COPYRIGHT %{buildroot}/usr/share/package-licenses/xorriso/90b747e2b215f2b36d0186df7f5d4d1553800e9a || :
cp %{_builddir}/xorriso-%{version}/libisofs/COPYRIGHT %{buildroot}/usr/share/package-licenses/xorriso/2236b80df839204a4250cd722f9f2178c77b387a || :
cp %{_builddir}/xorriso-%{version}/libjte/COPYRIGHT %{buildroot}/usr/share/package-licenses/xorriso/bccdf745d5afc092f29c0e6639dcc6282b6028e7 || :
cp %{_builddir}/xorriso-%{version}/xorriso/COPYRIGHT %{buildroot}/usr/share/package-licenses/xorriso/90b747e2b215f2b36d0186df7f5d4d1553800e9a || :
pushd ../buildavx2/
%make_install_v3
popd
%make_install
## Remove excluded files
rm -f %{buildroot}*/usr/bin/xorriso-tcltk
## install_append content
ln -s xorrisofs %{buildroot}/usr/bin/mkisofs
## install_append end
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/xorriso
/usr/bin/mkisofs
/usr/bin/osirrox
/usr/bin/xorrecord
/usr/bin/xorriso
/usr/bin/xorriso-dd-target
/usr/bin/xorrisofs

%files info
%defattr(0644,root,root,0755)
/usr/share/info/xorrecord.info
/usr/share/info/xorriso-dd-target.info
/usr/share/info/xorriso-tcltk.info
/usr/share/info/xorriso.info
/usr/share/info/xorrisofs.info

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/xorriso/2236b80df839204a4250cd722f9f2178c77b387a
/usr/share/package-licenses/xorriso/431ac668b8e0901320f42864b3f9361854690ff2
/usr/share/package-licenses/xorriso/8624bcdae55baeef00cd11d5dfcfa60f68710a02
/usr/share/package-licenses/xorriso/90b747e2b215f2b36d0186df7f5d4d1553800e9a
/usr/share/package-licenses/xorriso/a640a4b001c62a6f231213c9e10d5b985b05288b
/usr/share/package-licenses/xorriso/bccdf745d5afc092f29c0e6639dcc6282b6028e7

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/xorrecord.1
/usr/share/man/man1/xorriso-dd-target.1
/usr/share/man/man1/xorriso-tcltk.1
/usr/share/man/man1/xorriso.1
/usr/share/man/man1/xorrisofs.1
